name: Build deb

on:
  push:
    paths:
      - 'control' 
      - 'Tweak.xm' 
    branches:
      - 'main'  # 仅在推送到 main 分支时触发
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Bump package version
        run: |
          VERSION="1.0.0-${{ github.run_number }}"
          sed -i '' "s/^Version: .*/Version: ${VERSION}/" control
          echo "PACKAGE_VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Prepare Theos
        uses: axs66/theos-action@main

      - name: Build package
        run: |
          rm -f ${{ github.workspace }}/packages/*.deb
          make clean
          make package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
          make clean
          make package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=roothide

      - name: List generated Deb packages
        run: ls ${{ github.workspace }}/packages

      - name: 创建 Release
        if: (github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')) || github.event_name == 'workflow_dispatch'
        #if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')  //手动触发时，不创建 Release
        uses: softprops/action-gh-release@v1
        env:
          GH_TOKEN: ${{ secrets.PAT }}
        with:
          token: ${{ secrets.PAT }}
          tag_name: v${{ env.PACKAGE_VERSION }}
          name: 日月开关 v${{ env.PACKAGE_VERSION }}
          files: ${{ github.workspace }}/packages/*.deb

      - name: Upload specific Deb packages
        uses: actions/upload-artifact@v4.3.3
        with:
          name: 日月开关 v${{ env.PACKAGE_VERSION }}
          path: ${{ github.workspace }}/packages/*.deb
